
ALTER TABLE items DISABLE ROW LEVEL SECURITY;

ALTER TABLE sub_items DISABLE ROW LEVEL SECURITY;

ALTER TABLE projects NO FORCE ROW LEVEL SECURITY;

ALTER TABLE sub_projects NO FORCE ROW LEVEL SECURITY;
